apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore-postgres
  namespace: default
spec:
  type: state.postgresql
  version: v2
  metadata:
  - name: connectionString
    secretKeyRef:
      name: postgres-secret
      key: connection-string
  - name: tableName
    value: "dapr_state"
  - name: cleanupInterval
    value: "1h"
  - name: sslmode
    value: "require"
auth:
  secretStore: kubernetes
