apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: notification-service-reminders
  namespace: default
spec:
  pubsubname: pubsub-kafka
  topic: reminders
  routes:
    default: /events/reminders
  scopes:
  - notification-service

---
apiVersion: dapr.io/v2alpha1
kind: Subscription
metadata:
  name: notification-service-task-updates
  namespace: default
spec:
  pubsubname: pubsub-kafka
  topic: task-updates
  routes:
    default: /events/task-updates
  scopes:
  - notification-service
